/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface SupplyChainEnactmentInterface extends ethers.utils.Interface {
  functions: {
    "begin(uint256,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "begin",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "begin", data: BytesLike): Result;

  events: {
    "EndEvent()": EventFragment;
    "NonConformingTrace(uint256,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "EndEvent"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NonConformingTrace"): EventFragment;
}

export type EndEventEvent = TypedEvent<[] & {}>;

export type NonConformingTraceEvent = TypedEvent<
  [BigNumber, string] & { id: BigNumber; payload: string }
>;

export class SupplyChainEnactment extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SupplyChainEnactmentInterface;

  functions: {
    begin(
      id: BigNumberish,
      payload: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  begin(
    id: BigNumberish,
    payload: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    begin(
      id: BigNumberish,
      payload: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "EndEvent()"(): TypedEventFilter<[], {}>;

    EndEvent(): TypedEventFilter<[], {}>;

    "NonConformingTrace(uint256,bytes)"(
      id?: null,
      payload?: null
    ): TypedEventFilter<
      [BigNumber, string],
      { id: BigNumber; payload: string }
    >;

    NonConformingTrace(
      id?: null,
      payload?: null
    ): TypedEventFilter<
      [BigNumber, string],
      { id: BigNumber; payload: string }
    >;
  };

  estimateGas: {
    begin(
      id: BigNumberish,
      payload: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    begin(
      id: BigNumberish,
      payload: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
